services:
  ftsui:
    image: freetakserver-ui:latest
    build:
      context: ../UI/.
      dockerfile: Dockerfile
#    ports:
#      - 5000:5000
    volumes:
      - ./ui-config:/home/freetak/data:Z
    network_mode: "host"