name: Create Container Image for Tags

on:
  push:
    tags:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the container image
      run: docker build . --file Dockerfile --tag FTS-UI:${{ github.ref_name }}
      
