name: Developer container builds

on:
  push:

env:
  IMAGE_NAME: freetakteam/ui:${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build the container image
      # can this be converted to podman at some point to be more foss?
      run: docker build . --file Dockerfile --tag ghcr.io/$IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image to ghcr.io
      run: |
        echo IMAGE_NAME=$IMAGE_NAME
        docker push ghcr.io/$IMAGE_NAME

